# Generated by Django 5.2.1 on 2025-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='livewin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='countdown_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='scheduled_start',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='livewin',
            index=models.Index(fields=['-timestamp'], name='livewin_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='livewin',
            index=models.Index(fields=['visible'], name='livewin_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['scheduled_start', 'countdown_end'], name='app_offer_schedul_1211ef_idx'),
        ),
    ]
