# Generated by Django 5.2.1 on 2025-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_paymentmethod_options_alter_livewin_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-timestamp'], name='app_pagevis_timesta_921724_idx'), models.Index(fields=['path'], name='app_pagevis_path_41522a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('button_click', 'Button Click'), ('form_submit', 'Form Submission'), ('link_click', 'Link Click'), ('offer_interest', 'Offer Interest'), ('payment_click', 'Payment Method Click')], max_length=50)),
                ('element_id', models.CharField(blank=True, max_length=100, null=True)),
                ('page_path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-timestamp'], name='app_userint_timesta_7775c3_idx'), models.Index(fields=['type'], name='app_userint_type_f56c7c_idx')],
            },
        ),
    ]
