# Generated by Django 5.2.1 on 2025-06-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pagevisit_userinteraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Page Visit', 'verbose_name_plural': 'Page Visits'},
        ),
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Interaction', 'verbose_name_plural': 'User Interactions'},
        ),
        migrations.RemoveIndex(
            model_name='pagevisit',
            name='app_pagevis_timesta_921724_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagevisit',
            name='app_pagevis_path_41522a_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinteraction',
            name='app_userint_timesta_7775c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinteraction',
            name='app_userint_type_f56c7c_idx',
        ),
    ]
