# Generated by Django 5.2.1 on 2025-06-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pagevisit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='path',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active', 'scheduled_start'], name='app_offer_is_acti_b86a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active', 'countdown_end'], name='app_offer_is_acti_6e44f9_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['-timestamp', 'ip_address'], name='app_pagevis_timesta_713deb_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['session_key', 'is_active'], name='app_pagevis_session_2cdfda_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['-timestamp', 'type'], name='app_userint_timesta_a3d702_idx'),
        ),
    ]
