# Generated by Django 5.2.1 on 2025-06-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pagevisit_path_pagevisit_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
