# Generated by Django 5.2.1 on 2025-06-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pagevisit_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisit',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pagevisit',
            name='app_pagevis_timesta_713deb_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagevisit',
            name='app_pagevis_session_2cdfda_idx',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='is_active',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='session_key',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['-timestamp'], name='app_pagevis_timesta_921724_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['session_key'], name='app_pagevis_session_5f0602_idx'),
        ),
    ]
