# Generated by Django 5.2.1 on 2025-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pagevisit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='session_key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
