# Generated by Django 5.2.1 on 2025-06-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pagevisit_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
