# Generated by Django 5.2.1 on 2025-06-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_pagevisit_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='path',
        ),
    ]
