# Generated by Django 5.2.1 on 2025-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_pagevisit_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.CharField(default='Unknown', max_length=45),
        ),
    ]
