# Generated by Django 5.2.1 on 2025-06-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_pagevisit_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='last_update',
            new_name='last_activity',
        ),
    ]
