# Generated by Django 5.2.1 on 2025-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('analytics', models.BooleanField(default=False)),
                ('preferences', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'action'], name='app_analyti_categor_f41fd9_idx'), models.Index(fields=['timestamp'], name='app_analyti_timesta_6149f9_idx')],
            },
        ),
    ]
