# Generated by Django 5.2.1 on 2025-06-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cookieconsent_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='page_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='app.pagevisit'),
        ),
    ]
