# Generated by Django 5.2.1 on 2025-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userinteraction_page_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
