# Generated by Django 5.2.1 on 2025-06-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_pagevisit_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='event_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='is_conversion',
            field=models.BooleanField(default=False),
        ),
    ]
