# Generated by Django 5.2.1 on 2025-06-22 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_analyticsevent_event_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_id',
            field=models.CharField(blank=True, help_text='Your account ID/address for this payment method', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions for this payment method'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payments/qr_codes/'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('cashapp', 'CashApp'), ('bitcoin', 'Bitcoin'), ('venmo', 'Venmo'), ('paypal', 'PayPal'), ('chime', 'Chime'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='RechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='recharges/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paymentmethod')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
