# Generated by Django 5.2.1 on 2025-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_paymentmethod_account_id_paymentmethod_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookieconsent',
            old_name='consent_date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
    ]
