# Generated by Django 5.2.1 on 2025-06-25 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_consent_date_cookieconsent_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analyticsevent',
            name='app_analyti_timesta_6149f9_idx',
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='page_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pagevisit'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['-timestamp'], name='app_analyti_timesta_dfb4af_idx'),
        ),
    ]
